import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);

/**
 * Read the package.json paths touched by the current branch.
 *
 * Falls back to every publishable package when git cannot tell us (shallow
 * clone, no upstream, first commit), so `bump-version` is never a no-op by
 * accident.
 */
const changedPackageJsonPaths = () => {
  const fallback = findAllPackageJsonPaths();

  try {
    const output = execFileSync(
      'git',
      ['diff', 'HEAD^1', '--name-only', '--diff-filter=ACMR'],
      { cwd: rootDir, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
    );

    const changed = output
      .split('\n')
      .filter(Boolean)
      .filter((file) => file.endsWith('package.json'))
      .filter((file) => existsSync(path.join(rootDir, file)));

    return changed.length > 0 ? changed : fallback;
  } catch {
    return fallback;
  }
};

/** Every non-private package.json under `packages`. */
const findAllPackageJsonPaths = (dir = 'packages', found = []) => {
  const abs = path.join(rootDir, dir);

  if (!existsSync(abs)) return found;

  for (const entry of readdirSync(abs, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name === 'dist') continue;

    const rel = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      findAllPackageJsonPaths(rel, found);
    } else if (entry.name === 'package.json') {
      const manifest = JSON.parse(
        readFileSync(path.join(rootDir, rel), 'utf-8'),
      );

      if (!manifest.private) found.push(rel);
    }
  }

  return found;
};

const paths = changedPackageJsonPaths();

if (paths.length === 0) {
  console.error('No publishable package.json found.');
  process.exit(1);
}

console.log(`Bumping ${paths.length} package(s):`);
for (const file of paths) console.log(`  - ${file}`);

// `--no-verify` skips lifecycle scripts; bumpp must not re-trigger them.
execFileSync('npx', ['--yes', 'bumpp', '--no-verify', '--quiet', ...paths], {
  cwd: rootDir,
  stdio: 'inherit',
});

// Record what was bumped so the next publish can be scoped to these packages.
writeFileSync(
  path.join(rootDir, 'scripts/publish-to-npm.sh'),
  [
    '#!/bin/bash',
    '# Generated by scripts/bump-version.mjs — do not edit by hand.',
    '#',
    '# Publishes the packages whose version was just bumped.',
    '# Usage: scripts/publish-to-npm.sh [package ...]',
    '',
    'set -euo pipefail',
    '',
    'cd "$(dirname "$0")/.."',
    '',
    'node scripts/publish-ci.mjs "$@"',
    '',
  ].join('\n'),
);
execFileSync('chmod', ['+x', path.join(rootDir, 'scripts/publish-to-npm.sh')]);

console.log('\nUpdated scripts/publish-to-npm.sh');
console.log('Publish with: pnpm run publish-pkg');
