#!/bin/bash
# Generated by scripts/bump-version.mjs — do not edit by hand.
#
# Publishes the packages whose version was just bumped.
# Usage: scripts/publish-to-npm.sh [package ...]

set -euo pipefail

cd "$(dirname "$0")/.."

node scripts/publish-ci.mjs "$@"
